[workspace]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "mojo_test"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
modular = ">=25,<26"
numpy = ">=2.3.1,<3"
scipy = ">=1.16.0,<2"
python = "3.11.*"
cupy = ">=13.4.1,<14"
