[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gpu-intro"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025072205,<26"
